# Production profile overrides
spring:
  config:
    activate:
      on-profile: prod

sameboat:
  cors:
    allowed-origins:
      - https://sameboatplatform.org
      - https://app-sameboat.netlify.app
  cookie:
    secure: true
    domain: .sameboatplatform.org
  session:
    ttl-days: 14
